title: "José H C Monteiro da Silva"
author: "José H C Monteiro da Silva"
description: "University of Pennsylvania   |   josehcms@sas.upenn.edu"
baseurl: ""
url: "https://josehcms.github.io"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false             # show article excerpts instead of archive list on the home page
show_frame: true                # display a grey frame on large screens
show_sidebar: false             # show a sidebar instead of the usual header
show_minimal: false             # remove all clutter

#show_frame: "/assets/images/background.svg"

# Menu                          # for available icons see https://fontawesome.com/v5/icons/

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md",title: "About Me"}
  - {file: "research.md", title: "Research"}
  - {file: "teaching.md", title: "Teaching"}
  # - {file: "_posts/blog.md", title: "Demographic Thoughts"}
  - {file: "cv.md", title: "CV"}

    
external:                       # accepts {file, title, url, icon, sidebaricon}
  - {title: Mail, icon: envelope, url: "mailto:josehcms@sas.upenn.edu"}
  - {title: Github, icon: github, url: "https://github.com/josehcms"}
  - {title: linkedin, icon: linkedin, url: "https://www.linkedin.com/in/josehcms/"}
  #- {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""         # see https://disqus.com
#  isso_domain: ""              # see https://isso-comments.de

plugins:
 - jekyll-feed
